<Project Sdk="MSBuild.Sdk.Extras/3.0.23">
  <PropertyGroup>
    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <TargetFramework>uap10.0.19041</TargetFramework>
    <MinimumVisualStudioVersion>14</MinimumVisualStudioVersion>
    <EnableDotNetNativeCompatibleProfile>true</EnableDotNetNativeCompatibleProfile>
    <RootNamespace>GameEngine</RootNamespace>
    <AssemblyName>GameEngine</AssemblyName>
    <DefaultLanguage>en-US</DefaultLanguage>
    <OutputType>AppContainerExe</OutputType>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x64|ARM64</AppxBundlePlatforms>
    <PackageCertificateKeyFile>GameEngine_TemporaryKey.pfx</PackageCertificateKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsUniversal" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
  </ItemGroup>

  <ItemGroup>
    <AppxManifest Include="Package.appxmanifest">
      <SubType>Designer</SubType>
    </AppxManifest>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Game1.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
